# Generated by Django 3.2.8 on 2021-10-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_msg', models.CharField(default='', max_length=500)),
                ('upload_img', models.FileField(default='', upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
