# Generated by Django 3.2.8 on 2021-11-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imageupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='upload_img',
            new_name='image',
        ),
    ]
